Repository PlanIT-3/PlanIT-FE, pull requests merged in 2025-07, with the labels that each got.

#12 [REFACTOR] 추천 상품 페이지 카드 컴포넌트 분리
  src/components/common/CardContainer.vue
  src/components/common/OnboardingHeader.vue
  src/views/onBoarding/InvestmentSurveyView.vue
Labels: refactor

#21 [REFACTOR] 전체적인 파일명 및 위치 리팩토링
  src/assets/images/HeaderBack.png
  src/assets/images/background.png
  src/assets/images/etc/crater.png
  src/assets/images/etc/gaia.png
  src/assets/images/etc/logo.svg
  src/assets/images/etc/lunar.png
  src/assets/images/etc/nebula.png
  src/assets/images/etc/volcano.png
  src/assets/images/headerBackground.svg
  src/assets/images/invest-survey/ResultBack.png
  src/assets/logo.svg
Labels: refactor

#24 [REFACTOR] 이미지 위치 수정
  src/assets/images/crater.png
  src/assets/images/gaia.png
  src/assets/images/logo.svg
  src/assets/images/lunar.png
  src/assets/images/nebula.png
  src/assets/images/volcano.png
  src/components/common/MainHeader.vue
  src/components/common/OnboardingHeader.vue
  src/views/MainView.vue
  src/views/onBoarding/InvestmentSurveyResult.vue
Labels: refactor

#36 [FEAT] 리워드 UI 구성
  src/assets/images/star.png
  src/router/index.js
  src/views/reward/RewardView.vue
Labels: feat

#57 fix: #54 추천 페이지에 레이아웃 적용
  src/views/recommendation/RecommendView.vue
Labels: refactor

#65 [REFACTOR] 리워드 보상 수령 버튼시 레포트 열람 1회권 부여
  src/views/reward/RewardView.vue
Labels: refactor

#66 알림/알림설정 페이지
  src/components/alarm/AlarmItem.vue
  src/components/alarm/AlarmSettingItem.vue
  src/router/alarm.js
  src/router/index.js
  src/views/alarm/AlarmSettingView.vue
  src/views/alarm/AlarmView.vue
  src/views/auth/SignupView.vue
  src/views/onBoarding/LoginPage.vue
Labels: feat

#70 [BUG]: DefaultLayout 경로 수정
  src/views/alarm/AlarmSettingView.vue
  src/views/alarm/AlarmView.vue
Labels: fix

#68 [fix] mainview
  src/views/MainView.vue
Labels: refactor
